version: '3'
services:
  composer:
    image: composer:2.2
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  php:
    image: php:8.1-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app